### ISSUE TITLE
GraphQL Yoga results

### ISSUE THREAD

**Issue by ardatan** [graphql-crystal/benchmarks#20]
Hi!
This is Arda from @the-guild-org. I am one of maintainers of GraphQL Yoga, and we recently introduces a lot of performance improvements on GraphQL Yoga. I'd like to kindly ask if you can update the results based on the latest version of GraphQL Yoga's node package.

Thanks!

**Comment by jgillich** [comment]
Done :+1: 

Btw, if you guys have any suggestions to evolve the schema, I'm all ears

**Comment by ardatan** [comment]
Thank you for your quick response :) To have a fair comparison with Mercurius(which is JIT enabled by default), it'd nicer to have another scenario with Envelop's JIT plugin with Yoga and a small note that Mercurius has JIT.
