### ISSUE TITLE
Use codespaces for Benchmarks 

### ISSUE THREAD

**Issue by tusharmath** [graphql-crystal/benchmarks#235]
Currently the benchmarks run on GitHub actions which doesn't guarantee consistent cpu across runs. Its better to integrate it witg codespaces or setup a dedicated ci machine with consistent cpu.

**Comment by jgillich** [comment]
Simple solution: Run it yourself on a machine of your choice :wink: 

I don't think codespaces provides consistent CPU either, it's just another VM.
